In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=1)

In [7]:
X_train

age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
75    5    Male  102.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [8]:
si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.transform(X_test[['fever']])

In [9]:
X_train_fever

array([[101.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [100.95833333],
       [102.        ],
       [100.95833333],
       [102.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.95833333],
       [ 99.        ],
       [100.95833333],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [100

In [10]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [12]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [13]:
X_train_age= X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age= X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age

array([[42],
       [34],
       [20],
       [56],
       [42],
       [82],
       [79],
       [33],
       [19],
       [49],
       [65],
       [10],
       [60],
       [12],
       [ 5],
       [49],
       [66],
       [ 6],
       [80],
       [74],
       [25],
       [83],
       [ 8],
       [70],
       [17],
       [82],
       [72],
       [38],
       [19],
       [ 5],
       [22],
       [81],
       [13],
       [65],
       [23],
       [44],
       [73],
       [47],
       [31],
       [34],
       [15],
       [51],
       [68],
       [27],
       [18],
       [46],
       [19],
       [24],
       [60],
       [59],
       [49],
       [71],
       [81],
       [10],
       [20],
       [51],
       [64],
       [54],
       [16],
       [51],
       [34],
       [16],
       [65],
       [64],
       [12],
       [19],
       [23],
       [14],
       [75],
       [80],
       [27],
       [69],
       [42],
       [48],
       [84],
       [ 5],
       [64],

In [14]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [15]:
X_train_transformed

array([[ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 100.95833333,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 79.        , 100.95833333,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.    

This is very tiring so we do column tranformation

In [16]:
from sklearn.compose import ColumnTransformer

In [18]:
tranformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [21]:
tranformer.fit_transform(X_train).shape

(80, 7)

In [22]:
tranformer.fit_transform(X_test).shape

(20, 7)