In [2]:
import torch
print(torch.__version__)

2.8.0


In [3]:
if torch.backends.mps.is_available():
    print("Apple M1 GPU (MPS) is available.")
else:
    print("Apple M1 GPU (MPS) is not available.")

Apple M1 GPU (MPS) is available.


Creating Tensors


In [4]:
#using empty

a= torch.empty(2,3)

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.8188, 0.7232, 0.3026],
        [0.0449, 0.0867, 0.9335]])

In [9]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
# torch.rand_like(x) error for x is int but rand is float
x= x.to(torch.float32)
torch.rand_like(x) #torch.rand_like(x , dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical Operations

In [20]:
x = torch.rand(2,2)

In [21]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [22]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [23]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [24]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [25]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [26]:
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [27]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

element wise

In [28]:
a= torch.rand(2,3)
b= torch.rand(2,3)

In [29]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [30]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [31]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [32]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [33]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [34]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [35]:
torch.abs(a)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [36]:
torch.neg(a)

tensor([[-0.9969, -0.7565, -0.2239],
        [-0.3023, -0.1784, -0.8238]])

In [37]:
torch.round(a)

tensor([[1., 1., 0.],
        [0., 0., 1.]])

In [38]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [39]:
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [40]:
torch.clamp(a, min=2, max=3)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [41]:
e = torch.randint(size=(2,3), low=0 , high=10)

In [42]:
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [43]:
torch.sum(e)

tensor(24)

In [44]:
torch.sum(e , dim=0)

tensor([ 8,  0, 16])

In [45]:
torch.mean(e.to(torch.float) )

tensor(4.)

In [46]:
torch.median(e.to(torch.float) )

tensor(0.)

In [47]:
torch.min(e)

tensor(0)

In [48]:
torch.max(e)

tensor(9)

In [49]:
torch.prod(e)

tensor(0)

In [50]:
torch.std(e.to(torch.float))

tensor(4.4272)

In [51]:
torch.var(e.to(torch.float))

tensor(19.6000)

In [52]:
torch.argmax(e)

tensor(5)

In [53]:
torch.argmin(e)

tensor(1)

Matrix Operations

In [54]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [55]:
f,g

(tensor([[5, 7, 3],
         [9, 4, 0]]),
 tensor([[5, 7],
         [5, 9],
         [9, 7]]))

In [56]:
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [57]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

torch.dot(vec1, vec2)

tensor(11)

In [58]:
torch.transpose(f, 0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [59]:
g = torch.randint(size=(3,3), low=0, high=10 , dtype=torch.float32)

In [60]:
torch.det(g)

tensor(-110.)

In [61]:
torch.inverse(g)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

Comparisons

In [62]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [63]:
i,j

(tensor([[7, 8, 3],
         [6, 1, 5]]),
 tensor([[5, 0, 4],
         [3, 8, 8]]))

In [64]:
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [65]:
i<j

tensor([[False, False,  True],
        [False,  True,  True]])

In [66]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [67]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [68]:
i>=j

tensor([[ True,  True, False],
        [ True, False, False]])

In [69]:
i<=j

tensor([[False, False,  True],
        [False,  True,  True]])

Special Functions

In [70]:
k = torch.randint(size=(2,3), low=0, high=10)

In [71]:
k

tensor([[3, 3, 5],
        [0, 6, 4]])

In [72]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [73]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5982]])

In [74]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [75]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [76]:
torch.softmax(k.to(torch.float16), dim=0)

tensor([[0.9526, 0.0474, 0.7310],
        [0.0474, 0.9526, 0.2690]], dtype=torch.float16)

In [77]:
torch.relu(k)

tensor([[3, 3, 5],
        [0, 6, 4]])

Inplace Operations

In [78]:
m= torch.rand(2,3)
n= torch.rand(2,3)

In [79]:
m.add_(n) 

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [80]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [81]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

Copy a tensor

In [82]:
b=a

In [83]:
b,a

(tensor([[0.9969, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]),
 tensor([[0.9969, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]))

In [84]:
a[0][0]=0

In [85]:
a,b

(tensor([[0.0000, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]),
 tensor([[0.0000, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]))

In [86]:
id(a),id(b)

(4498295920, 4498295920)

In [87]:
b= a.clone()

In [88]:
id(a),id(b)

(4498295920, 4498858256)

tensor operation on gpu

In [89]:
torch.backends.mps.is_available()

True

In [90]:
device = torch.device('mps')

In [91]:
#creating a new tensor on gpu

torch.rand((2,3), device=device)

tensor([[0.4643, 0.8532, 0.4872],
        [0.4602, 0.4261, 0.0968]], device='mps:0')

In [92]:
# mode an existing tensors to gpu
a

tensor([[0.0000, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [93]:
a =a.to(device)

In [94]:
a+7

tensor([[7.0000, 7.7565, 7.2239],
        [7.3023, 7.1784, 7.8238]], device='mps:0')

In [96]:
import time

size=20000

#cpu
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start_time= time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

#cpu
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time= time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.mps.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 8.2391 seconds
Time on GPU: 7.8825 seconds


Reshaping Tensor

In [97]:
a = torch.ones(4,4)

In [98]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [100]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
b= torch.rand(2,3,4)
b

tensor([[[0.9306, 0.0754, 0.2309, 0.9891],
         [0.0892, 0.8956, 0.6463, 0.5519],
         [0.2341, 0.9145, 0.1475, 0.5748]],

        [[0.0045, 0.2032, 0.4069, 0.4558],
         [0.1485, 0.4870, 0.3654, 0.0266],
         [0.8018, 0.4941, 0.6959, 0.1562]]])

In [102]:
b.permute(2,0,1)

tensor([[[0.9306, 0.0892, 0.2341],
         [0.0045, 0.1485, 0.8018]],

        [[0.0754, 0.8956, 0.9145],
         [0.2032, 0.4870, 0.4941]],

        [[0.2309, 0.6463, 0.1475],
         [0.4069, 0.3654, 0.6959]],

        [[0.9891, 0.5519, 0.5748],
         [0.4558, 0.0266, 0.1562]]])

In [103]:
b.shape

torch.Size([2, 3, 4])

In [104]:
c = torch.rand(226,226,3)

In [106]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [107]:
d = torch.rand(1,20)

In [111]:
d.shape

torch.Size([1, 20])

In [110]:
d.squeeze(0).shape

torch.Size([20])

Numpy and PyTorch

In [112]:
a = torch.tensor([1,2,3])

In [113]:
b= a.numpy()

In [114]:
type(b)

numpy.ndarray

In [115]:
torch.from_numpy(b)

tensor([1, 2, 3])