In [2]:
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self , features):
        
        out = self.linear(features) #z= wx + b
        out = self.sigmoid(out)
        
        return out

In [3]:
features =torch.rand(10,5)

In [4]:
model = Model(features.shape[1])

model(features)# will call forward automatically

tensor([[0.4446],
        [0.4544],
        [0.3354],
        [0.3989],
        [0.4219],
        [0.4509],
        [0.4221],
        [0.4011],
        [0.5238],
        [0.4793]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.2885, -0.2511,  0.1755, -0.3956, -0.3856]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([-0.0291], requires_grad=True)

In [8]:
from torchinfo import summary

summary(model , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [9]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self , features):
        
        out = self.linear1(features) #z= wx + b
        out = self.relu(out)
        out= self.linear2(out)
        out = self.sigmoid(out)
        
        return out

In [10]:
model = Model(features.shape[1])

model(features)# will call forward automatically

tensor([[0.3845],
        [0.3713],
        [0.3737],
        [0.3954],
        [0.3758],
        [0.3842],
        [0.3980],
        [0.3777],
        [0.3975],
        [0.3953]], grad_fn=<SigmoidBackward0>)

In [12]:
model.linear1.weight

Parameter containing:
tensor([[-0.1661,  0.3757, -0.3605,  0.0780, -0.3076],
        [ 0.2850,  0.1153,  0.2148, -0.3920,  0.2655],
        [-0.1169, -0.3343, -0.0793, -0.0952, -0.2054]], requires_grad=True)

In [13]:
summary(model , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self , features):
        
        out = self.network(features)
        
        return out

In [15]:
model = Model(features.shape[1])

model(features)# will call forward automatically

tensor([[0.6054],
        [0.6185],
        [0.5828],
        [0.6057],
        [0.5984],
        [0.6097],
        [0.6013],
        [0.6009],
        [0.6000],
        [0.5893]], grad_fn=<SigmoidBackward0>)