In [77]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [79]:
df.shape

(569, 33)

In [80]:
df.drop(columns=['id','Unnamed: 32'] , inplace=True)

In [81]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [82]:
x_train, x_test , y_train , y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [83]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [84]:
x_train

array([[-0.48413657, -0.39010711, -0.42522326, ..., -0.63414043,
        -0.58220576,  0.53114515],
       [-0.32647871, -0.7718446 , -0.35564835, ..., -0.14241678,
         0.76692914,  0.65786705],
       [-1.23315472,  0.12960779, -1.2317923 , ..., -1.40317155,
        -1.60060613,  0.32219483],
       ...,
       [ 1.10104153,  1.17363683,  0.98002333, ..., -0.01910051,
        -0.66734534, -0.26354193],
       [-0.34941076, -0.72815176, -0.38731118, ..., -0.87923153,
         1.13368426, -0.7625446 ],
       [ 1.84060021,  1.93941144,  1.77992651, ...,  0.63910011,
        -0.77704442, -0.04952273]], shape=(455, 30))

In [85]:
y_train

431    B
292    B
97     B
178    B
204    B
      ..
150    B
201    M
274    M
268    B
233    M
Name: diagnosis, Length: 455, dtype: object

In [86]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [87]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,

Numpy to PyTorch tensor 

In [88]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [89]:
y_test

tensor([0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [90]:
x_train.shape

torch.Size([455, 30])

Defining the MODEL

In [91]:
from torch.utils.data import Dataset, DataLoader

In [92]:
class CustomDataset(Dataset):
    
    def __init__(self, features , labels):
        
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index] , self.labels[index]

In [93]:
train_dataset = CustomDataset(x_train, y_train)
test_dataset = CustomDataset(x_test , y_test)

In [94]:
train_dataset[10]

(tensor([-0.3551,  0.4585, -0.3769, -0.3956, -1.4801, -0.4001, -0.3500, -0.7903,
         -0.8726, -0.2422,  0.3803,  0.9835, -0.1507,  0.0393, -0.3344,  1.0600,
          0.6148,  0.2523,  0.6924,  1.4745, -0.3831,  0.1845, -0.4617, -0.4095,
         -1.7019, -0.3953, -0.4366, -0.9068, -0.6935, -0.1492],
        dtype=torch.float64),
 tensor(0))

In [95]:
train_loader = DataLoader(train_dataset , batch_size=32 , shuffle=True)
test_loader = DataLoader(test_dataset , batch_size=32 , shuffle=True)

In [96]:
import torch
import torch.nn as nn

In [97]:
class MySimpleNN(nn.Module):
    
    def __init__(self , num_features):
        
        super().__init__()
        
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
        
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
    

    

In [98]:
learning_rate = 0.1
epochs = 25

In [99]:
model = MySimpleNN(x_train.shape[1])
optimizer = torch.optim.SGD(model.parameters() ,lr= learning_rate)
loss_function= nn.BCELoss()

Training PipeLine

In [100]:

for epoch in range(epochs):
    
    for batch_features , batch_labels in train_loader:
        # Convert to float32 for compatibility with model
        batch_features = batch_features.float()
        batch_labels = batch_labels.float()
        
        #forward pass
        y_pred = model(batch_features)
        
        #loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1,1))
        
        #zero grad for next epoch not needed accumulate for grad
        # It is better to make it zero before calculation than after 
        optimizer.zero_grad()
        #backward pass 
        loss.backward()
        #parameter update
        optimizer.step()
        
        print(loss.item())

0.5917378664016724
0.5023120641708374
0.3807840943336487
0.3998999297618866
0.41964149475097656
0.36639702320098877
0.3756979703903198
0.2889895439147949
0.319125235080719
0.23466867208480835
0.17239990830421448
0.280934602022171
0.20080295205116272
0.17076347768306732
0.18621240556240082
0.24036629498004913
0.19003361463546753
0.20351293683052063
0.08528584241867065
0.17722156643867493
0.33800122141838074
0.10814216732978821
0.2001778781414032
0.1764877885580063
0.20727556943893433
0.11291255056858063
0.15349003672599792
0.15960699319839478
0.1598135530948639
0.18364670872688293
0.10579673200845718
0.19495370984077454
0.16320398449897766
0.1334691196680069
0.16872866451740265
0.09232033789157867
0.13741958141326904
0.1622103452682495
0.07966747879981995
0.11976273357868195
0.161888986825943
0.12060415744781494
0.11995897442102432
0.20332710444927216
0.14600543677806854
0.08077554404735565
0.11157085746526718
0.1259976625442505
0.09957569092512131
0.12218571454286575
0.1996595859527588

In [101]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.3674,  0.5765,  0.5776,  0.4860,  0.2698,  0.1735,  0.3400,  0.5435,
           0.2439, -0.2582,  0.6023, -0.1127,  0.3328,  0.4489,  0.1378, -0.2394,
          -0.1076,  0.1039, -0.1027, -0.3633,  0.6613,  0.9023,  0.7750,  0.6085,
           0.4930,  0.2336,  0.4328,  0.6752,  0.2784,  0.0622]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.6048], requires_grad=True))

In [102]:
#model evaluation
model.eval()
accuracy_list= []

with torch.no_grad():
    for batch_features , batch_labels in test_loader:
        # Convert batch_features to float32 for compatibility
        batch_features = batch_features.float()
        
        y_pred = model(batch_features)
        y_pred = (y_pred>0.8).float()
        
        batch_accuracy = (y_pred.view(-1)== batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
    
overall_accuracy = sum(accuracy_list)/ len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')
    

Accuracy: 0.9453
